### ISSUE TITLE
Support for complex variables?

### ISSUE THREAD

**Issue by dvij** [JuliaOpt/Convex.jl#103]
Is it possible to add support for complex variables, and psd constraints on Hermitian matrices?

**Comment by mlubin** [comment]
Related issue: https://github.com/cvxgrp/cvxpy/issues/191

**Comment by marcusps** [comment]
I have been using the mapping in the introductory section of paper [arXiv:1007.2905](http://arxiv.org/pdf/1007.2905v2.pdf).  It is not so clear to me how to use this mapping in combination with some of the atoms in `Convex.jl` (like `logdet`, `lambdamin`) but it has worked well for many straight-forward complex-valued semidefinite programs.

Does anyone know of other references for complex-to-real correspondence?

**Comment by Ayush-iitkgp** [comment]
Hi @marcusps, I was going trough the pdf you referred in your comment above . It seems like the procedure the authors have mentioned are very mathematical especially in terms of group theory than providing an algorithm. I am interested to know how have you been approaching the problem of complex-to-real correspondence which would help me in my GSoc proposal.

Not sure about the exact approach followed by PICOS(http://picos.zib.de/complex.html) but it does solve some special cases of complex semi-definite programming.
Thanks

**Comment by madeleineudell** [comment]
The basic idea for how to implement complex SDPs is to represent
complex variables using both a real and imaginary part, both of which
can be implemented as standard scalar variables. Then the standard
machinery of Convex.jl would produce a complex semidefinite program.
To transform it into a real semidefinite program, we'd need to rewrite
the complex constraints as real constraints. For example, if z = x +
iy is a complex variable and we have ||z|| <= c (so, (z, c) is in the
second order cone), then (x, y, c) is also in the second order cone,
since ||z|| = sqrt(x^2 + y^2). To implement this, we'd need to

1) write similar transformations for the nonnegative and SDP cones
2) implement the transformation to and from the version of the problem
using only real variables
3) implement the infrastructure needed to carry complex variables
through Convex.jl and make them friendly to use

We might actually be able to operate just on the standard conic form
(c, A, b, cones) of the problem, which means we *could* integrate the
transformation into MathProgBase to make it even more widely
available! We'd take complex valued c, A, and b, and transform them to
real c, A, and b, then transform the solution back to a complex valued
solution x.

**Comment by marcusps** [comment]
@Ayush-iitkgp I was refering to discussion at the very beggining of the paper, and that portion is not all that involved. You can look [here](https://github.com/BBN-Q/SchattenNorms.jl/blob/master/src/dnorm.jl) for an example where I manually implement the transformation for a particular SDP. It may not be as efficient and general as what @madeleineudell is proposing, but until general support for complex matrices is implemented, this is a relatively simple workaround.

**Comment by Ayush-iitkgp** [comment]
Hi @marcusps, during the summers I have tried to provide support for complex variables in Convex.jl. You might want to try it and give your suggestions. Please find the development branch [here](https://github.com/Ayush-iitkgp/Convex.jl/tree/gsoc2/). You may also want to get started by reading this introductory post [here](https://ayush-iitkgp.github.io/posts/announcing-support-for-complex-domain-linear-programs-in-convexjl/).

**Comment by marcusps** [comment]
Hi Ayush

I still haven't gotten around to trying it out, but it is on my queue of
things to try.

Marcus
