### ISSUE TITLE
expose eig(X) function

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Convex.jl#134]
Thank you!

**Comment by chriscoey** [comment]
So that we can implement det(root_n(X)) = geo_mean(eig(X)). See #132

**Comment by madeleineudell** [comment]
Hi Chris! Thanks for following up. I started to build the function you
wanted and it's basically done, except that Convex.jl only has a two
argument version of geomean, rather than the n argument version needed
here. I'll try to get to this over the weekend, or you can try your hand at
it.

**Comment by madeleineudell** [comment]
Ok! Here's a mathematical approach to the problem. As far as I can see CVX actually uses an exponential cone representation under the hood for geomean (and then approximates the exponential cone with linear inequalities, I think, which we don't implement) so we'll have to roll our own.

log(det(X)) = log(lambda_1 \cdots lambda_n). Any function that is monotonic in the product lambda_1 \cdots lambda_n will have the same maximizer, so it will suit the needs of your problem.

We can easily represent t <= (x_1 x_2)^(1/2) using an SOC representation; that's what the current geomean function does. Composing this function recursively, we can represent the constraint t <= (x_1 \cdots x_n)^(1/n) whenever n is a power of 2. If n is not a power of 2, we can pad the vector x with 1s to reach \bar n, the smallest power of 2 greater than n, to represent the constraint t <= (x_1 \cdots x_n)^(1/\bar n). 

I think we should be able to represent (x_1 \cdots x_n)^(1/n) for any n, but I haven't been able to work it out yet.

The function (x_1 \cdots x_n)^(1/\bar n) is monotonic in the product x_1 \cdots x_n, so when applied to eig(X) it has the same maximizer as logdet, but uses only the SOC cone. Is that enough for your needs?

**Comment by madeleineudell** [comment]
Ah yes: and we can represent (x_1 \cdots x_n)^(1/n) as ((x_1 \cdots x_n)^(1/\bar n))^(\bar n / n), but we need to implement rational powers, which should be possible using the same tricks we use to make [rational norms](https://github.com/JuliaOpt/Convex.jl/blob/master/src/atoms/second_order_cone/rationalnorm.jl)...

**Comment by chriscoey** [comment]
Thank you so much Madeleine, this could be really helpful for us. 

Where are the functions you worked on? Are they on a local branch?

**Comment by madeleineudell** [comment]
I just pushed the work to [this branch](https://github.com/JuliaOpt/Convex.jl/tree/nthroot_det). 

The main function that will be useful to you is sgeomean_eig, which computes (a monotonic increasing function of) the geometric mean of the eigenvalues of the matrix, or equivalently, (a monotonic increasing function of) the nth root of the determinant of the matrix. The monotonic increasing function is x^(\nbar / n), where \nbar is the smallest power of 2 bigger than n.

The relevant code is in the [nthroot_det](https://github.com/JuliaOpt/Convex.jl/blob/nthroot_det/src/atoms/sdp_cone/nthroot_det.jl) function and in the [sgeomean](https://github.com/JuliaOpt/Convex.jl/blob/nthroot_det/src/atoms/second_order_cone/geomean.jl#L53) function.

I haven't been able to figure out how to compute the actual geometric mean yet, which is why I'm waiting before putting it into master. The approach in my last comment doesn't work, because sgeomean is concave increasing and x^(\nbar / n) is convex. If you can figure out a different way to implement geomean (rather than this scaled version) in Convex, let me know...! But the current version still does what you want: it is a monotonic increasing function of the product of the eigenvalues, so is maximized at the same place that logdet is if there's nothing else in the objective.

**Comment by madeleineudell** [comment]
Also, better tests for this function would be extremely helpful: they'd go
at the end of test/test_sdp.jl.

On Mon, Apr 4, 2016 at 12:45 PM, Chris C. <notifications@github.com> wrote:

> Thank you so much Madeleine, this could be really helpful for us.
>
> Where are the functions you worked on? Are they on a local branch?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/134#issuecomment-205464681>
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by chriscoey** [comment]
thanks Madeleine. I tested the new sgeomean_eig atom and it works as expected on my example (as in, same solution as logdet gives)!

my example is the d-optimal experimental design problem taken from CVX examples and the Boyd textbook. should I try adding it to the test set on your branch nthroot_det and doing a pull request on that branch? or do you prefer I give you the code for the example and you add it in?

**Comment by madeleineudell** [comment]
I'd prefer a PR on this branch. Thanks!
