### ISSUE TITLE
MethodError: no method matching diagind(::Convex.Variable)

### ISSUE THREAD

**Issue by sxl19910525** [JuliaOpt/Convex.jl#227]
My code is as follow, but it gets error when I run it,
`using Convex
m = 5;  
A = randn(m, m); 
x = Semidefinite(5);
xx=x;xx[diagind(xx)].=0;
obj=vecnorm(A-x,2)+sumabs(xx)*0.01;
pro= minimize(obj, [x >= 0]);
pro.constraints+=[x[diagind(x)].=1];`
the error as follow
> MethodError: no method matching diagind(::Convex.Variable)

 How can fix th eproblem here?

**Comment by ericphanson** [comment]
It looks like your question was answered here: <https://stackoverflow.com/questions/49966042/julia-error-using-convex-package-with-diagind-function>. In particular, you can't use inplace assignment instead of constraints, so I don't think this problem can really be formulated in a way to use `diagind`. If one really did need to use `diagind` with a `Variable`, then I think
```julia
import LinearAlgebra: diagind
diagind(x::AbstractExpr) = diagind(size(x)...)
```
would do the job, and could possible be added to `Convex`. I'm not quite sure what the use would be though, since most formulations I can think of would be better off using `diag`.
