### ISSUE TITLE
Switch to MathOptInterface

### ISSUE THREAD

**Issue by ararslan** [JuliaOpt/Convex.jl#262]
It is intended to supersede MathProgBase. JuMP is also making this transition.

**Comment by mlubin** [comment]
One option to consider is to use JuMP instead of MOI. JuMP is intended to be a user-friendly interface to MOI, and there's very little loss of performance in using it.

**Comment by blegat** [comment]
> Would it make sense to effectively transform Convex into a JuMP extension in the same sense as e.g. PolyJuMP?

Yes, I think it would. In terms of syntax, the problem:
```julia
x = Variable(4, Negative())
z = Semidefinite(4)
problem = minimize(objective)
problem.constraints += constraint1
problem.constraints += constraint2
solve!(problem)
```
It could become:
```julia
x = Variable(4, Negative())
z = Semidefinite(4)
problem = minimize(objective)::JuMP.Model
@constraint(problem, constraint1)
@constraint(problem, constraint2)
JuMP.optimize!(problem, with_optimizer(SCS.Optimizer))
```
in which case, all Convex has to implement is
```julia
function minimize(objective)
     model = JuMP.Model()
     JuMP.set_objective_sense(model, MOI.MIN_SENSE)
     objective_function::JuMP.AbstractJuMPScalar = ... # transformed from `objective`
     JuMP.set_objective_function(model, objective_function)
end
function JuMP.build_constraint(_error::Function, func::ConvexExpression, set)
    if # func and set makes a convex constraint
        jump_function, jump_set = # transform in JuMP constraint by transforming Convex variables to JuMP variables (creating some on the fly if it is the first time it appears on a constraint)
        return JuMP.build_constraint(_error, jump_function, jump_set)
    else
         _error("not convex")
    end
end
```
All the features of constraints such as names, containers of constraints, ... would be available, e.g. one could do
```julia
@constraint(problem, name[i=1:3], logsumexp(x[i]) <= f(i^2 + 1))
```

**Comment by mlubin** [comment]
Turning Convex into a JuMP extension is a much more extensive change than leaving Convex's syntax as is and replacing the small part of the code that uses MathProgBase with a small piece of code that uses JuMP. It also increases the maintenance burden because JuMP's extension API changes more quickly than the regular JuMP API. The syntax benefits would be nice, but just want to make sure the trade-offs are stated explicitly up front.

**Comment by ararslan** [comment]
It seems like a good long-term goal, but perhaps not the most practical in the short term.

**Comment by ericphanson** [comment]
I would vote for going directly to MathOptInterface instead of through JuMP, as JuMP converts all numbers to Float64, and I am interested in using higher precision numeric types.

**Comment by ericphanson** [comment]
I have an MOI branch here: https://github.com/ericphanson/Convex.jl/tree/MathOptInterface. It seems to work (most tests pass) except I haven't yet passed the dual values back to Convex from MOI, or filled in some of the interface for asking if a solver supports various things (which is why some tests fail). There aren't many tests for dual variables (https://github.com/JuliaOpt/Convex.jl/issues/290), so that should be sorted out first to make sure I don't break things when I (or someone else) implements populating dual variables. @JiazhengZhu and I are using the branch to try to get the high precision solver SDPA-GMP working with Convex through MOI.
