### ISSUE TITLE
README example fails

### ISSUE THREAD

**Issue by scottstanie** [JuliaOpt/Convex.jl#300]
When running the first example in the README, it fails with the following versions installed on Julia 1.1.0:

```
(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [f65535da] Convex v0.12.2
  [c946c3f1] SCS v0.5.1
```

```julia
julia> # Solve the problem by calling solve!
       solve!(problem)
ERROR: ArgumentError: The provided problem hasn't been initialized with a conic model.
            You can resolve this by passing in `AbstractMathProgSolver` such as:
            solve!(problem, ECOSSolver())
```

Running that suggested command also fails (even if I run `using SCS`) with 
```
julia> # Solve the problem by calling solve!
       solve!(problem, ECOSSolver() )
ERROR: UndefVarError: ECOSSolver not defined
```

though if I can get it to work by running 
```julia
solve!(problem, SCSSolver() )
```

Not sure which parts of it you'd want to update, but let me know if you want to just add the `using SCS` and change it to `solve!(problem, SCSSolver() )`

**Comment by ericphanson** [comment]
Good catch, it looks like I forgot to update the readme when I updated the docs in #271. Thanks!

Just to be clear, the reason `ECOSSolver()` didn't work is that you need `using ECOS` for that one (instead of `using SCS`). ECOS and SCS are just two different solvers. I proposed a change to the error message in #301 to add the `using ECOS` line to the error message (along with the update for the readme), so hopefully that will help for the next user.

**Comment by brilhana** [comment]
Some of the examples have to be updated as well, see #261.
