### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by juliohm** [JuliaOpt/Convex.jl#309]
I can't emphasise more how this package is useful for quickly trying out ideas. Could you please tag a new version? The master branch is working, whereas the latest tag is not.

**Comment by ericphanson** [comment]
I think @ararslan is the release tagger here; I'm sure he will tag one soon especially since you asked. But in the meantime just to say-- the only things (besides docs) that should have changed since the last release are about the function `fix!(x::Variable, v)` where `v` is the value you want to fix `x` too. Both bugs in the release version can be worked around by instead doing

```julia
x.value = v
fix!(x)
```

So that should work in the meantime.

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/2663
