### ISSUE TITLE
helping with updating Examples

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaOpt/Convex.jl#338]
Hi,

I would like to make a PR for updating some of the finance examples (portfolio_optimization...) you have.  However, I ask for some instructions.

1. Do you prefer a miniminal update, or a bit more (improving the style, fixing the LaTeXing, and perhaps even improving the link to standard "finance" approaches)?
2. The current examples use both SCS and ECOS. I would probably start with SCS and only use ECOS if needed. OK?
3...and one more thing: the examples include plots (using various packages). Should I perhaps standardise this to PyPlot.jl or Plots.jl?

**Comment by ericphanson** [comment]
I'm very glad to hear it! For point 1, I think either way is fine. The most important thing is getting the code running on Julia 1.0 so that users can play around with it themselves without running into errors. Besides that, I think any extra references or styles fixes are nice to have too.

For the solvers, I think any open source solver that can be automatically installed is fine (that way the users don't have to do anything more than add the packages). So ECOS, SCS, GLPK, etc-- as you wish.

For plotting packages, I don't have a strong preference, I would lean a bit towards standardizing towards one package. It would be nice to have a single `Project.toml` file that can be used for all the examples to install all the packages we need (which is what JuMP does: https://github.com/JuliaOpt/JuMP.jl/tree/master/examples), and if that has a bunch of different packages then that's more upfront loading time to get it all installed.

What do you think? I think if you're the one putting in the time to update examples, your opinion probably counts the most :). 

One thing that I think is important, however, is https://github.com/JuliaOpt/Convex.jl/issues/335. I think it would be great to generate the notebooks instead of writing them directly, since that makes reviewing PRs and seeing the changes much easier, and also allows writing to multiple output formats. I think it could even be nice to have the examples in a way that we could include them directly in the documentation (under a subsection), along with links to notebooks for users to run and modify themselves. It seems like Literate can do this: https://fredrikekre.github.io/Literate.jl/stable/documenter/, and it seems like Literate is what was used for the JuliaAcademy resources: https://github.com/JuliaComputing/JuliaAcademyMaterials/. I think we could use their `unliterate` script to transform the current notebooks into literate files, or https://github.com/oxinabox/ipynb2Literate.jl (I haven't tried either but both seem to have the same goal).

I think at some point it would be nice to even include the examples as part of our continuous integration, so that every PR is checked against all the examples to make sure they don't break with new changes (once they all run, that is). It seems easier to do this with simple `.jl` files with comments  (which is what literate uses) than jupyter notebooks.

**Comment by ericphanson** [comment]
Actually, I'll try to do #335 tonight, so then you can focus just on the content instead of the formatting.

**Comment by PaulSoderlind** [comment]
Thanks for the reply. I'll then do a moderate update and start with SCS. 

As for the plotting, I guess the two main alternatives are Plots and PyPlot. I use the former for my teaching and the latter for my own code, so I have no strong recommendation for Convex.jl. Please settle for one of them and ask contributors to use that.

Weave&Literate are indeed the way forward. I'll give it a try, but I might (if I get into a rush, which is likely) end up submitting old-fashioned notebooks. Then you can decide what to do with them.
