### ISSUE TITLE
quadform returns a 1x1 matrix

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaOpt/Convex.jl#341]
while I had expected a number (from `quadform(Vector,Matrix)`. In contrast, `dot` indeed gives a number.

**Comment by ericphanson** [comment]
Thanks for pointing this out. I agree, the convention in Convex is to return `(1,1)` objects as scalars and `(n,1)` objects as vectors, even though internally they are treated all as matrices.

I think changing this is breaking, since code that uses it currently will break if we change it to return a scalar, and it is built into the tests currently. I'm planning on having a breaking release soon though with #330 and #336, so we should do this at the same time.

**Comment by ericphanson** [comment]
Just a brief update: I tracked this down to `evaluate` on `Constant`s giving sizes with the extra 1s. Doing the naive fix there caused massive test failures so I think the next step is to look into why and likely fix other code in Convex relying on this behavior. I think that is where this fix should be made though.
