### ISSUE TITLE
problem.status == :Optimal (on master)

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaOpt/Convex.jl#354]
does not seem to work on master. However, `problem.status == MOI.OPTIMAL` does. In case this is well known, forget about this issue.

**Comment by blegat** [comment]
Convex just switched from MathProgBase to MathOptInterface which reports statuses with enum instead of symbols. See https://www.juliaopt.org/MathOptInterface.jl/v0.9.7/apireference/#MathOptInterface.TerminationStatusCode

**Comment by ericphanson** [comment]
See also https://github.com/JuliaOpt/Convex.jl/issues/346. We switched to MOI on master but haven’t really settled on an API to interact with it yet, which is why one reason it’s not released yet. Feel free to add any suggestions to that issue. For example, we could reexport the MOI termination statuses. It might be worth checking what JuMP does too.

I’ll close this in favor of discussing over on that issue.
