### ISSUE TITLE
Wrong indices in documentation of `conv(h,x)` ?

### ISSUE THREAD

**Issue by riccardomurri** [JuliaOpt/Convex.jl#364]
[Documentation of `conv(h,x)`][1] currently states:

    h∈R^m x∈R^m h∗x∈R^{m+n−1} entry i is given by ∑_{j=1,…,m} h_j ⋅ x_{i−j}

it looks to me there's two things to fix:

1. dimension of `x` is `n`, not `m`: `x∈R^n`
2. for the definition to make sense, one must have `1 <= i-j <= n` for all `j`, hence `1+m <= i <= n+1`, so `h∗x∈R^{n−m+1}` (signs changed w.r.t. to current docs)

[1]: http://www.juliaopt.org/Convex.jl/stable/operations/#Linear-Program-Representable-Functions-1

**Comment by ericphanson** [comment]
Thanks for pointing this out.

Looking at [the source](https://github.com/JuliaOpt/Convex.jl/blob/master/src/atoms/affine/conv.jl), I agree that `x∈R^n`. But it looks like `h∗x∈R^{m+n−1}` is right too, since we implement the convolution as a matrix multiplication, and [our "convolution operator"](https://github.com/JuliaOpt/Convex.jl/blob/5d71eb4c6dabbfcc8cbcc2f90b859f9d1535ef1a/src/atoms/affine/conv.jl#L12) is `(m + n - 1) × n`. One can check this with simple examples:

```julia
julia> n = 4; m = 11;

julia> n+m-1
14

julia> a = Variable(n); a.value = rand(n);

julia> b = rand(m)
11-element Array{Float64,1}:
 ...

julia> evaluate(conv(a,b))
14-element Array{Float64,1}:
 ...
```

I see what you mean about the indexing though. I wonder if the summation expression is quite right...

**Comment by riccardomurri** [comment]
> But it looks like h∗x∈R^{m+n−1} is right too

Ah, I see Convex.jl is [extending x with 0's][1], then indices are fine but I think it should be mentioned in the docs...

[1]: https://github.com/JuliaOpt/Convex.jl/blob/5d71eb4c6dabbfcc8cbcc2f90b859f9d1535ef1a/src/atoms/affine/conv.jl#L14

**Comment by ericphanson** [comment]
Ah I get it now. There's the zeros, and also the indexing is off by one. I'll put up a PR in a minute.

**Comment by riccardomurri** [comment]
Changes suggested in #365 look good to me and would indeed answer my questions :-)

Thanks a lot for the discussion and the fix!
