### ISSUE TITLE
Type error on examples

### ISSUE THREAD

**Issue by BenStrowbridge** [JuliaOpt/Convex.jl#67]
I am getting a type error on problem specification line using the code in the Quick Example on the Convex.jl web page:

problem = minimize(sum_squares(A * x + b), [x >= 0])
 generates this error:
LoadError: TypeError: non-boolean (Convex.EqConstraint) used in boolean context
while loading In[3], in expression starting on line 1

 in hash at hashing2.jl:184
 in call at C:\Users\bens\.julia\v0.4\Convex\src\atoms/affine/add_subtract.jl:82
 in + at C:\Users\bens\.julia\v0.4\Convex\src\atoms/affine/add_subtract.jl:119

I also get a similar error at this line from the Linear Program example in the basic usage notebook:

p.constraints += [x >= 1; x <= 10; x[2] <= 5; x[1] + x[4] - x[2] <= 10]
(here the error is at line 117 instead of 119; I also sometimes get errors on line 122 of add_subtract.jl)

[Julia 0.4.0-dev+3442 on Win7x64 with the Convex package loaded today (ver 0.0.4)]

**Comment by karanveerm** [comment]
This is unfortunate. This is happening because of https://github.com/JuliaLang/julia/commit/0179028021bda3c40b1032031ca9fccb322bfdfd#diff-bd039b573830c906952620ffc6354809R184

We override the `==` operator, so `x1==x2` returns a `Constraint` object. So `if x1==x2` is not valid since you can only use the `if` statement in a boolean context.

**Comment by madeleineudell** [comment]
It might be time to change the way we compute our unique ids in Convex.jl.

For expressions, we could hash a string concatenating of the name (head) of
the atom, along with the unique ids of its children.

Constants can be hashed by asking for the object id of the object they wrap
(be it a number or array).

And for Variables, I guess we'll need to be slightly fancier. We could have
a global variable counter we increment. Any other suggestions?

On Sat, Feb 21, 2015 at 1:44 AM, Karanveer Mohan <notifications@github.com>
wrote:

> This is unfortunate. This is happening because of JuliaLang/julia@0179028
> #diff-bd039b573830c906952620ffc6354809R184
> <https://github.com/JuliaLang/julia/commit/0179028021bda3c40b1032031ca9fccb322bfdfd#diff-bd039b573830c906952620ffc6354809R184>
>
> We override the == operator, so x1==x2 returns a Constraint object. So if
> x1==x2 is not valid since you can only use the if statement in a boolean
> context.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/67#issuecomment-75364253>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by karanveerm** [comment]
I'm doing what Tony suggested at https://github.com/JuliaLang/julia/issues/10267 and simply using the old hash function. If we have more problems with `==` as Julia develops, we might have to reconsider using that altogether, but I think things are fine for now.

@BenStrowbridge I have fixed the error for you. However, you will probably see a few deprecation warnings from other packages that are being used because you are on the latest Julia build. You might consider using v0.3.6. Otherwise, we'll probably get rid of the deprecation warnings soon. Let us know if you run into other problems!

**Comment by tkelman** [comment]
BTW you might find https://github.com/JuliaLang/Compat.jl useful for getting rid of 0.4 deprecation warnings without hurting 0.3 support.
